-- 1. Check row count
-- 2. Check NULLs
-- 3. Check duplicates
-- 4. Check date format
-- 5. Check negative sales/profit


-------------- 1. ROW COUNT --------------
-- CHECK TOTAL ROW COUNT
SELECT COUNT(*) AS TOTAL_ORDER_COUNT
FROM PROJECT.SUPERSTORE;

-- VIEW SAMPLE DATA
SELECT *
FROM PROJECT.SUPERSTORE
LIMIT 100;
    
    
-------------- 2. CHECK NULLS IN KEY BUSINESS COLUMNS ---------------
SELECT 
	SUM(SALES IS NULL)        AS SALES_NULLS,
	SUM(PROFIT IS NULL)       AS PROFIT_NULLS,
	SUM(ORDER_DATE IS NULL)   AS ORDER_DATE_NULLS,
	SUM(CUSTOMER_ID IS NULL)  AS CUSTOMER_ID_NULLS
FROM PROJECT.SUPERSTORE;

-- NULL PERCENTAGE FOR ORDER_ID
SELECT 
	COUNT(*) AS TOTAL_ROWS,
	SUM(ORDER_ID IS NULL) AS NULL_COUNT,
	ROUND((SUM(ORDER_ID IS NULL) / COUNT(*)) * 100, 2) AS NULL_PERCENTAGE
FROM PROJECT.SUPERSTORE;


-------------- 3. IDENTIFY DUPLICATES --------------
WITH DUPLICATES AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_DATE, SALES, PROFIT, QUANTITY ORDER BY ROW_ID) AS RN
    FROM PROJECT.SUPERSTORE
)

DELETE FROM PROJECT.SUPERSTORE
WHERE ROW_ID IN (
    SELECT ROW_ID 
    FROM DUPLICATES 
    WHERE RN > 1
);
-- VERIFICATION
SELECT *
FROM PROJECT.SUPERSTORE
WHERE CUSTOMER_ID = 'RB-19795'
  AND ORDER_DATE = '2016-04-15'
  AND PRODUCT_ID = 'TEC-AC-10004659';


-------------- 4. DATE CLEANING --------------
-- CONVERT STRING TO DATE
UPDATE PROJECT.SUPERSTORE
SET ORDER_DATE = STR_TO_DATE(ORDER_DATE, '%m/%d/%Y');

UPDATE PROJECT.SUPERSTORE
SET SHIP_DATE = STR_TO_DATE(SHIP_DATE, '%m/%d/%Y');

-- MODIFY DATA TYPE
ALTER TABLE PROJECT.SUPERSTORE
MODIFY ORDER_DATE DATE;

ALTER TABLE PROJECT.SUPERSTORE
MODIFY SHIP_DATE DATE;

-- VERIFY DATE RANGE
SELECT 
    MIN(ORDER_DATE) AS MIN_DATE,
    MAX(ORDER_DATE) AS MAX_DATE
FROM PROJECT.SUPERSTORE;


-------------- 5. NEGATIVE SALES / QUANTITY --------------
SELECT COUNT(*) AS NEGATIVE_RECORDS
FROM PROJECT.SUPERSTORE
WHERE SALES < 0 
   OR QUANTITY <= 0;


-------------- 6. SALES SUMMARY  --------------
SELECT 
    ROUND(MIN(SALES), 2)  AS MIN_REVENUE,
    ROUND(MAX(SALES), 2)  AS MAX_REVENUE,
    ROUND(AVG(SALES), 2)  AS AVG_REVENUE,
    ROUND(SUM(SALES), 2)  AS TOTAL_REVENUE
FROM PROJECT.SUPERSTORE;


-------------- 7. PROFIT SUMMARY  --------------
SELECT 
    ROUND(MIN(PROFIT), 2) AS MIN_PROFIT,
    ROUND(MAX(PROFIT), 2) AS MAX_PROFIT,
    ROUND(AVG(PROFIT), 2) AS AVG_PROFIT,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    round(SUM(PROFIT)/SUM(SALES) * 100, 2) AS PROFIT_MARGIN
FROM PROJECT.SUPERSTORE;